package model;
// Generated Feb 29, 2020 6:06:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="hatkhola"
    , uniqueConstraints = @UniqueConstraint(columnNames="customer_id") 
)
public class Customer  implements java.io.Serializable {


     private Long id;
     private String customerId;
     private String customerName;
     private String contactNo;
     private String email;
     private String password;
//     private Set<Cart> carts = new HashSet(0);
//     private Set<Orders> orderses = new HashSet(0);
//     private Set<Wishlist> wishlists = new HashSet(0);

    public Customer() {
    }

	
    public Customer(String customerId) {
        this.customerId = customerId;
    }
    public Customer(String customerId, String customerName, String contactNo, String email, String password, Set carts, Set orderses, Set wishlists) {
       this.customerId = customerId;
       this.customerName = customerName;
       this.contactNo = contactNo;
       this.email = email;
       this.password = password;
//       this.carts = carts;
//       this.orderses = orderses;
//       this.wishlists = wishlists;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="customer_id", unique=true, nullable=false, length=20)
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="customer_name", length=120)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    
    @Column(name="contact_no", length=20)
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    
    @Column(name="email", length=150)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

//@OneToMany(fetch=FetchType.EAGER, mappedBy="customer")
//    public Set<Cart> getCarts() {
//        return this.carts;
//    }
//    
//    public void setCarts(Set<Cart> carts) {
//        this.carts = carts;
//    }
//
//@OneToMany(fetch=FetchType.EAGER, mappedBy="customer")
//    public Set<Orders> getOrderses() {
//        return this.orderses;
//    }
//    
//    public void setOrderses(Set<Orders> orderses) {
//        this.orderses = orderses;
//    }
//
//@OneToMany(fetch=FetchType.EAGER, mappedBy="customer")
//    public Set<Wishlist> getWishlists() {
//        return this.wishlists;
//    }
    
//    public void setWishlists(Set<Wishlist> wishlists) {
//        this.wishlists = wishlists;
//    }




}


