package model;
// Generated Feb 29, 2020 6:06:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="hatkhola"
    , uniqueConstraints = @UniqueConstraint(columnNames="order_id") 
)
public class Orders  implements java.io.Serializable {


     private Long id;
     private Customer customer;
     private Product product;
     private String orderId;
     private String color;
     private String psize;
     private Integer quantity;
     private String paymentMethod;
     private String address;
     private String contact;
     private Date orderDate;

    public Orders() {
    }

	
    public Orders(Customer customer, Product product, String orderId, Date orderDate) {
        this.customer = customer;
        this.product = product;
        this.orderId = orderId;
        this.orderDate = orderDate;
    }
    public Orders(Customer customer, Product product, String orderId, String color, String psize, Integer quantity, String paymentMethod, String address, String contact, Date orderDate) {
       this.customer = customer;
       this.product = product;
       this.orderId = orderId;
       this.color = color;
       this.psize = psize;
       this.quantity = quantity;
       this.paymentMethod = paymentMethod;
       this.address = address;
       this.contact = contact;
       this.orderDate = orderDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="order_id", unique=true, nullable=false, length=20)
    public String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    
    @Column(name="color", length=50)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="psize", length=10)
    public String getPsize() {
        return this.psize;
    }
    
    public void setPsize(String psize) {
        this.psize = psize;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="payment_method", length=100)
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    
    @Column(name="address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="contact", length=20)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_date", nullable=false, length=19)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }




}


